// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// DireDi Mirrors-Free Generator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by dire_di mirrors-free code generator
// Entry point: example/app_module.dart
// Components found: 5

import 'package:dire_di_flutter/dire_di.dart';

import 'controllers/user_controller.dart';
import 'repositories/user_repository.dart';
import 'services/database_service.dart';
import 'services/user_service.dart';

extension GeneratedDependencies on DireContainer {
  /// Register all discovered components from the entire project
  void registerGeneratedDependencies() {
    // Register UserRepository
    register<UserRepository>(
      () {
        final instance = UserRepository();
        instance.databaseService = get<DatabaseService>();
        instance.configService = get<ConfigurationService>();
        return instance;
      },
    );

    // Register UserController
    register<UserController>(
      () {
        final instance = UserController();
        instance.userService = get<UserService>();
        return instance;
      },
    );

    // Register DatabaseService
    register<DatabaseService>(
      DatabaseService.new,
    );

    // Register ConfigurationService
    register<ConfigurationService>(
      ConfigurationService.new,
    );

    // Register UserService
    register<UserService>(
      () {
        final instance = UserService(get<ConfigurationService>());
        instance.userRepository = get<UserRepository>();
        return instance;
      },
    );
  }
}
