// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// DiGenerator
// **************************************************************************

// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by dire_di code generator

import 'package:dire_di/dire_di.dart';
import 'autowired_example.dart';

extension GeneratedDependencies on DireContainer {
  /// Register all discovered components
  void registerGeneratedDependencies() {
    // Register DatabaseService
    register<DatabaseService>(
      () => DatabaseService(),
      scope: ScopeType.singleton,
    );

    // Register ConfigurationService
    register<ConfigurationService>(
      () => ConfigurationService(),
      scope: ScopeType.singleton,
    );

    // Register UserRepository
    register<UserRepository>(
      () {
        final instance = UserRepository();
        instance.databaseService = get<DatabaseService>();
        instance.configService = get<ConfigurationService>();
        return instance;
      },
      scope: ScopeType.singleton,
    );

    // Register UserService
    register<UserService>(
      () {
        final instance = UserService(get<ConfigurationService>());
        instance.userRepository = get<UserRepository>();
        return instance;
      },
      scope: ScopeType.singleton,
    );

    // Register UserController
    register<UserController>(
      () {
        final instance = UserController();
        instance.userService = get<UserService>();
        return instance;
      },
      scope: ScopeType.singleton,
    );
  }
}
