targets:
  $default:
    builders:
      dire_di_flutter|di_mirrors_free_generator:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - example/**.dart

builders:
  di_generator:
    target: ":di_generator"
    import: "package:dire_di_flutter/builder.dart"
    builder_factories: ["diBuilder"]
    build_extensions: { ".dart": [".dire_di.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]

  di_aggregating_generator:
    target: ":di_aggregating_generator"
    import: "package:dire_di_flutter/builder.dart"
    builder_factories: ["diAggregatingBuilder"]
    build_extensions: { ".dart": [".dire_di.dart"] }
    auto_apply: dependents
    build_to: source

  di_mirrors_free_generator:
    target: ":di_mirrors_free_generator"
    import: "package:dire_di_flutter/builder.dart"
    builder_factories: ["diMirrorsFreeBuilder"]
    build_extensions: { ".dart": [".dire_di.dart"] }
    auto_apply: dependents
    build_to: source
